version: "2.0"
services:
  spacedeck:
    depends_on:
      - spacedeck_db
    image: spacedeck:latest
    ports:
      - "9666:9666"
    volumes:
      - ./config:/app/config
      - ./storage:/app/storage
      # - ./database.sqlite:/app/database.sqlite
  spacedeck_db:
    image: postgres:12.2
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "spacedeck"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
